---
title: "The binomial distribution"
teaching: 10
exercises: 2
---

:::::::::::::::::::::::::::::::::::::: questions 

- What is the binomial distribution and?  
- What kind of data is it used on?

::::::::::::::::::::::::::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::: objectives



::::::::::::::::::::::::::::::::::::::::::::::::

## Overview probability distributions

The binomial distribution is what we have just seen in the example: We use it when we have a fixed sample size and count the number of "successes" in that sample -- for example mutations in a genome, or the number of cells within a sample that show a certain phenotype.

TRANSLATE VIDEO


:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: instructor

Inline instructor notes can help inform instructors of timing challenges
associated with the lessons. They appear in the "Instructor View"

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::: challenge 

## Challenge 1: Which of the following statements are true?  

We are in a diagnostic laboratory that gets blood samples from incoming hospital patients and tests them for some disease. Which of these experiments can be modeled with a binomial distribution?

1. Counting the total number of samples that get tested over one day.  
2. Counting the number of positive samples out of 50 samples that get tested successively.  
3. Measuring all the blood sample's volumes (in mL).  


:::::::::::::::::::::::: solution 

## Solution
 
Counting the number of positive samples out of 50 samples that get tested successively.

:::::::::::::::::::::::::::::::::


## Challenge 2: Discrete distributions

What is the probability of an outcome of X=1.5 in a discrete distribution?

- 0 
- 0.5 
- 0.15 

:::::::::::::::::::::::: solution 

The value $1.5$ is not discrete, and can therefore not occur in a discrete distribution. Its probability is zero. 

:::::::::::::::::::::::::::::::::
::::::::::::::::::::::::::::::::::::::::::::::::

